# Generated by Django 4.0.2 on 2023-03-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='rows',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='seats_in_row',
            field=models.IntegerField(),
        ),
    ]
