# Generated by Django 4.0.2 on 2022-07-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='show_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
