# Generated by Django 4.0.2 on 2023-02-17 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descriptor',
            new_name='description',
        ),
    ]
