# Generated by Django 4.0.2 on 2023-10-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesession',
            old_name='cinema',
            new_name='cinema_hall',
        ),
    ]
