# Generated by Django 4.0.2 on 2023-06-13 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_cinemahall_movie_moviesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinemahall",
            name="rows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cinemahall",
            name="seats_in_row",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="moviesession",
            name="show_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
