# Generated by Django 4.0.2 on 2025-05-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='text',
            new_name='description',
        ),
    ]
