# Generated by Django 4.1.3 on 2022-12-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_cinemahall_movie_moviesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
