# Generated by Django 5.1.7 on 2025-03-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='seats_per_row',
            new_name='seats_in_row',
        ),
    ]
