# Generated by Django 4.0.2 on 2023-11-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genders',
            new_name='genres',
        ),
    ]
