# Generated by Django 4.0.2 on 2025-02-04 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesession',
            name='cinema_halls',
        ),
        migrations.RemoveField(
            model_name='moviesession',
            name='movies',
        ),
        migrations.AddField(
            model_name='moviesession',
            name='cinema_hall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='db.cinemahall'),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='db.movie'),
        ),
    ]
