# Generated by Django 4.0.2 on 2025-04-14 13:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('db', '0003_alter_moviesession_show_time'), ('db', '0004_alter_moviesession_show_time')]

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='show_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='show_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
