# Generated by Django 5.2.6 on 2025-09-08 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesession',
            name='cinema_hall',
        ),
        migrations.AddField(
            model_name='moviesession',
            name='cinema_hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.cinemahall'),
        ),
    ]
