# Generated by Django 4.0.2 on 2022-10-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
