# Generated by Django 4.0.2 on 2023-01-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descriptions',
            new_name='description',
        ),
    ]
