# Generated by Django 5.2.1 on 2025-05-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
    ]
