# Generated by Django 4.0.2 on 2023-02-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='desription',
            new_name='description',
        ),
    ]
