# Generated by Django 5.2.1 on 2025-05-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='show_time',
            field=models.DateTimeField(null=True),
        ),
    ]
