# Generated by Django 4.0.2 on 2025-11-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='sets_in_row',
            new_name='sits_in_row',
        ),
    ]
