# Generated by Django 4.1.2 on 2025-01-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_cinemahall_movie_moviesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinemahall",
            name="rows",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="cinemahall",
            name="seats_in_row",
            field=models.IntegerField(default=1),
        ),
    ]
