# Generated by Django 4.0.2 on 2025-07-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesession',
            old_name='cinemaHall',
            new_name='cinema_hall',
        ),
    ]
