# Generated by Django 4.0.2 on 2025-03-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='capacity',
            field=models.IntegerField(editable=False),
        ),
    ]
