# Generated by Django 4.0.2 on 2023-07-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_cinemahall_movie_moviesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesession',
            old_name='ciname_hall',
            new_name='cinema_hall',
        ),
    ]
