# Generated by Django 4.0.2 on 2023-03-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_cinemahall_rows_alter_cinemahall_seats_in_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='movie'),
        ),
    ]
