# Generated by Django 4.0.2 on 2024-08-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_genre_movie_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actor',
            new_name='actors',
        ),
    ]
