# Generated by Django 4.0.2 on 2024-10-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_seats_per_row_cinemahall_seats_in_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='discription',
            new_name='description',
        ),
    ]
