# Generated by Django 4.0.2 on 2023-09-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_moviesession_cinema_hall_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='seats_in_a_row',
            new_name='seats_in_row',
        ),
    ]
