# Generated by Django 4.0.2 on 2023-06-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_cinemahall_rows_cinemahall_seats_in_row_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(related_name="genre", to="db.Genre"),
        ),
    ]
