# Generated by Django 4.0.2 on 2025-02-24 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_movie_actors_alter_movie_genders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='seat_in_row',
            new_name='seats_in_row',
        ),
    ]
