# Generated by Django 4.0.2 on 2025-01-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_moviesession_cinema_hall_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='gerne',
            new_name='genre',
        ),
    ]
