# Generated by Django 4.0.2 on 2025-03-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_cinemahall_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemahall',
            name='capacity',
        ),
    ]
