# Generated by Django 4.0.2 on 2025-04-29 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_moviesession_cinema_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.movie'),
        ),
    ]
