# Generated by Django 4.0.2 on 2025-11-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_sets_in_row_cinemahall_sits_in_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='sits_in_row',
            new_name='seats_in_row',
        ),
    ]
