# Generated by Django 4.0.2 on 2023-04-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_moviesession_show_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
