# Generated by Django 4.0.2 on 2025-04-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_seat_in_row_cinemahall_seats_in_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
