# Generated by Django 4.0.2 on 2023-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
