# Generated by Django 4.0.2 on 2024-04-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_movie_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descriptions',
            new_name='description',
        ),
    ]
