# Generated by Django 4.0.2 on 2022-06-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_cinemahall_rows_cinemahall_seats_in_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='show_time',
            field=models.DateTimeField(null=True),
        ),
    ]
