# Generated by Django 5.2.1 on 2025-05-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20250507_2145'),
    ]

    operations = [
    ]
