# Generated by Django 4.0.2 on 2024-11-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_moviesession_show_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesession',
            old_name='cinema_hall',
            new_name='CinemaHall',
        ),
        migrations.RenameField(
            model_name='moviesession',
            old_name='movie',
            new_name='Movie',
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='actors_in_movies', to='db.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movie_genres', to='db.Genre'),
        ),
    ]
