# Generated by Django 4.0.2 on 2024-03-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_cinemahall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='seats_per_row',
            new_name='seats_in_row',
        ),
    ]
