# Generated by Django 4.1.2 on 2025-01-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_cinemahall_rows_cinemahall_seats_in_row"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
