# Generated by Django 4.0.2 on 2023-09-10 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_alter_moviesession_show_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                related_name="movies", to="db.Actor"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                related_name="movie_genres", to="db.Genre"
            ),
        ),
        migrations.AlterField(
            model_name="moviesession",
            name="show_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
