# Generated by Django 4.0.2 on 2024-03-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_moviesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='db.Actor'),
        ),
    ]
