# Generated by Django 4.0.2 on 2022-06-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_moviesession_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='rows',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='seats_in_row',
            field=models.IntegerField(),
        ),
    ]
