# Generated by Django 4.0.2 on 2025-04-29 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_moviesession_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='cinema_hall',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='db.cinemahall'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.movie'),
            preserve_default=False,
        ),
    ]
