# Generated by Django 4.0.2 on 2024-11-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_rename_cinema_hall_moviesession_cinemahall_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesession',
            old_name='CinemaHall',
            new_name='cinema_hall',
        ),
        migrations.RenameField(
            model_name='moviesession',
            old_name='Movie',
            new_name='movie',
        ),
    ]
