# Generated by Django 4.0.2 on 2025-02-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_rename_seat_in_row_cinemahall_seats_in_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genders',
            new_name='genres',
        ),
    ]
