# Generated by Django 4.0.2 on 2023-04-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='rows',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='seats_in_row',
            field=models.IntegerField(null=True),
        ),
    ]
