# Generated by Django 4.0.2 on 2025-01-11 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_moviesession_cinema_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='rows',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='seats_in_row',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='cinema_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_sessions', to='db.cinemahall'),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.movie'),
        ),
    ]
