# Generated by Django 4.0.2 on 2025-04-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_moviesession_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
