# Generated by Django 5.1.6 on 2025-02-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_rename_genders_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='show_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
