# Generated by Django 4.0.2 on 2022-10-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
